In [214]:
import pandas as pd
pd.__version__

'3.0.3'

## Series

In [215]:
data=[10,20,30,40,50]
s=pd.Series(data)
print(type(s))

print(s)

<class 'pandas.Series'>
0    10
1    20
2    30
3    40
4    50
dtype: int64

In [216]:
s.values

array([10, 20, 30, 40, 50])

In [217]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [218]:
# using labled index

labelled_data=pd.Series([1, "John",3.5, "Hey"], index=["Ronit","b","c","d"])
labelled_data

Ronit       1
b        John
c         3.5
d         Hey
dtype: object

In [219]:
labelled_data.index

Index(['Ronit', 'b', 'c', 'd'], dtype='str')

## Dictionary to Series

In [220]:
# creating using dictionary
import numpy as np

score = {"jane":90,"bill":80,"elon":85,"tom":75,"tim":95,"gp":None}
names=pd.Series(score) # convert to series
names

jane    90.0
bill    80.0
elon    85.0
tom     75.0
tim     95.0
gp       NaN
dtype: float64

In [221]:
names["tim"]

np.float64(95.0)

## Boolean Indexing

In [222]:
names[names>=85]

jane    90.0
elon    85.0
tim     95.0
dtype: float64

## Modifying Values

In [223]:
names["Tom"]=60
names[names<=80]=83
names

jane    90.0
bill    83.0
elon    85.0
tom     83.0
tim     95.0
gp       NaN
Tom     83.0
dtype: float64

## Checking Membership

In [224]:
"tom" in names

True

In [225]:
"can" in names

False

In [226]:
names["Ronit"]=18

In [227]:
if "Ronit" in names:
    print("whats up bro?")
else:
    print("nothing")

whats up bro?

## Operations

In [228]:
data=pd.Series([1,2,np.nan,4,5])
data.mean()

np.float64(3.0)

In [229]:
score={"jane":90,"Bil":80,"elon":85,"tom":np.nan,"tim":95,"gp":None}
names=pd.Series(score) # convert to series
names

jane    90.0
Bil     80.0
elon    85.0
tom      NaN
tim     95.0
gp       NaN
dtype: float64

In [230]:
names.isnull()

jane    False
Bil     False
elon    False
tom      True
tim     False
gp       True
dtype: bool

In [231]:
names.isna()

jane    False
Bil     False
elon    False
tom      True
tim     False
gp       True
dtype: bool

In [232]:
names.isna().any()

np.True_

In [233]:
names_without_na=names.dropna(inplace=False)

In [234]:
names

jane    90.0
Bil     80.0
elon    85.0
tom      NaN
tim     95.0
gp       NaN
dtype: float64

In [235]:
names.isnull()

jane    False
Bil     False
elon    False
tom      True
tim     False
gp       True
dtype: bool

In [236]:
names_without_na

jane    90.0
Bil     80.0
elon    85.0
tim     95.0
dtype: float64

In [237]:
names["Ronit"]=np.nan

In [238]:
names

jane     90.0
Bil      80.0
elon     85.0
tom       NaN
tim      95.0
gp        NaN
Ronit     NaN
dtype: float64

In [239]:
names.fillna(10,inplace=True)

jane     90.0
Bil      80.0
elon     85.0
tom      10.0
tim      95.0
gp       10.0
Ronit    10.0
dtype: float64

In [240]:
names

jane     90.0
Bil      80.0
elon     85.0
tom      10.0
tim      95.0
gp       10.0
Ronit    10.0
dtype: float64

In [241]:
names_without_na

jane    90.0
Bil     80.0
elon    85.0
tim     95.0
dtype: float64

## Data Frame

In [242]:
## creating a dataframe

data={
    "name":["bill","tom","tim","john","alex","vanessa","kate"],
    "score":[90,80,85,75,95,60,65],
    "sport":["wrestling","football","skiing","swimming","tennis","karete","surfing"],
    "gender":["M","M","M","M","F","F","F"]
}

df=pd.DataFrame(data)

In [243]:
df

      name  score      sport gender
0     bill     90  wrestling      M
1      tom     80   football      M
2      tim     85     skiing      M
3     john     75   swimming      M
4     alex     95     tennis      F
5  vanessa     60     karete      F
6     kate     65    surfing      F

In [244]:
interested_col_df=df[["name","score","sport"]]

In [245]:
interested_col_df

      name  score      sport
0     bill     90  wrestling
1      tom     80   football
2      tim     85     skiing
3     john     75   swimming
4     alex     95     tennis
5  vanessa     60     karete
6     kate     65    surfing

In [246]:
df.head()

   name  score      sport gender
0  bill     90  wrestling      M
1   tom     80   football      M
2   tim     85     skiing      M
3  john     75   swimming      M
4  alex     95     tennis      F

In [247]:
df.tail(5)

      name  score     sport gender
2      tim     85    skiing      M
3     john     75  swimming      M
4     alex     95    tennis      F
5  vanessa     60    karete      F
6     kate     65   surfing      F

In [248]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    7 non-null      str
 1   score   7 non-null      int64
 2   sport   7 non-null      str
 3   gender  7 non-null      str
dtypes: int64(1), str(3)
memory usage: 356.0 bytes

In [249]:
df.describe()

           score
count   7.000000
mean   78.571429
std    12.817399
min    60.000000
25%    70.000000
50%    80.000000
75%    87.500000
max    95.000000

In [250]:
df.sample(n=3,random_state=42)

      name  score      sport gender
0     bill     90  wrestling      M
1      tom     80   football      M
5  vanessa     60     karete      F

In [251]:
df.columns

Index(['name', 'score', 'sport', 'gender'], dtype='str')

## Accessing and Indexing Data in Data frame

In [252]:
# Accessing a single column
name_data_frame=df["name"]
#name_data_frame
# Accessing multiple columns
df[["name","sport","score"]]

      name      sport  score
0     bill  wrestling     90
1      tom   football     80
2      tim     skiing     85
3     john   swimming     75
4     alex     tennis     95
5  vanessa     karete     60
6     kate    surfing     65

In [253]:
# Accessing a specific row by index
print(df.iloc[2]) # third row (index 2)
# Ascessing a range of rows using slicing
print(df.iloc[1:4,0:2]) # rows with indices 1 2 3

name         tim
score         85
sport     skiing
gender         M
Name: 2, dtype: object
   name  score
1   tom     80
2   tim     85
3  john     75

In [254]:
df.set_index("name",inplace=True)

In [255]:
df

         score      sport gender
name
bill        90  wrestling      M
tom         80   football      M
tim         85     skiing      M
john        75   swimming      M
alex        95     tennis      F
vanessa     60     karete      F
kate        65    surfing      F

In [256]:
df.reset_index(inplace=True)
df

      name  score      sport gender
0     bill     90  wrestling      M
1      tom     80   football      M
2      tim     85     skiing      M
3     john     75   swimming      M
4     alex     95     tennis      F
5  vanessa     60     karete      F
6     kate     65    surfing      F

In [257]:
df.set_index("name",inplace=True)
df

         score      sport gender
name
bill        90  wrestling      M
tom         80   football      M
tim         85     skiing      M
john        75   swimming      M
alex        95     tennis      F
vanessa     60     karete      F
kate        65    surfing      F

In [258]:
# acessing row by label (name)
print(df.loc["bill"])

score            90
sport     wrestling
gender            M
Name: bill, dtype: object

In [259]:
# ascessing specific value using lables
print(df.loc["bill","score"]) # score of the person at index 1

90

## Slicing

In [260]:
print(df.loc["bill":"tim", "score":"gender"])

      score      sport gender
name
bill     90  wrestling      M
tom      80   football      M
tim      85     skiing      M

In [261]:
print(df.iloc[1:4,0:3])

      score     sport gender
name
tom      80  football      M
tim      85    skiing      M
john     75  swimming      M

In [262]:
df[df["gender"]=='M']

      score      sport gender
name
bill     90  wrestling      M
tom      80   football      M
tim      85     skiing      M
john     75   swimming      M

In [263]:
print(df[(df["score"]>80) & (df["gender"]=="M")])

      score      sport gender
name
bill     90  wrestling      M
tim      85     skiing      M

In [264]:
print(df.sort_values("score",ascending=True))

         score      sport gender
name
vanessa     60     karete      F
kate        65    surfing      F
john        75   swimming      M
tom         80   football      M
tim         85     skiing      M
bill        90  wrestling      M
alex        95     tennis      F

In [265]:
print(df.sort_values(by=["gender","score"],ascending=[True,False]))

         score      sport gender
name
alex        95     tennis      F
kate        65    surfing      F
vanessa     60     karete      F
bill        90  wrestling      M
tim         85     skiing      M
tom         80   football      M
john        75   swimming      M

## Importing and Exporting data

In [266]:
dataset=pd.read_csv("datasets 2/datasets/data.txt", sep="\t")
dataset

  name  score gender
0  Tim     80      M
1  Tom     85      M
2  Kim     70      F
3  Sam     90      M
4  Efe     75      M