In [125]:
import pandas as pd
pd.__version__

'3.0.3'

## Series

In [126]:
data=[10,20,30,40,50]
s=pd.Series(data)
print(type(s))

print(s)

<class 'pandas.Series'>
0    10
1    20
2    30
3    40
4    50
dtype: int64

In [127]:
s.values

array([10, 20, 30, 40, 50])

In [128]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [129]:
# using labled index

labelled_data=pd.Series([1, "John",3.5, "Hey"], index=["Ronit","b","c","d"])
labelled_data

Ronit       1
b        John
c         3.5
d         Hey
dtype: object

In [130]:
labelled_data.index

Index(['Ronit', 'b', 'c', 'd'], dtype='str')

## Dictionary to Series

In [131]:
# creating using dictionary
import numpy as np

score = {"jane":90,"bill":80,"elon":85,"tom":75,"tim":95,"gp":None}
names=pd.Series(score) # convert to series
names

jane    90.0
bill    80.0
elon    85.0
tom     75.0
tim     95.0
gp       NaN
dtype: float64

In [132]:
names["tim"]

np.float64(95.0)

## Boolean Indexing

In [133]:
names[names>=85]

jane    90.0
elon    85.0
tim     95.0
dtype: float64

## Modifying Values

In [134]:
names["Tom"]=60
names[names<=80]=83
names

jane    90.0
bill    83.0
elon    85.0
tom     83.0
tim     95.0
gp       NaN
Tom     83.0
dtype: float64

## Checking Membership

In [135]:
"tom" in names

True

In [136]:
"can" in names

False

In [137]:
names["Ronit"]=18

In [138]:
if "Ronit" in names:
    print("whats up bro?")
else:
    print("nothing")

whats up bro?

## Operations

In [139]:
data=pd.Series([1,2,np.nan,4,5])
data.mean()

np.float64(3.0)

In [140]:
score={"jane":90,"Bil":80,"elon":85,"tom":np.nan,"tim":95,"gp":None}
names=pd.Series(score) # convert to series
names

jane    90.0
Bil     80.0
elon    85.0
tom      NaN
tim     95.0
gp       NaN
dtype: float64

In [141]:
names.isnull()

jane    False
Bil     False
elon    False
tom      True
tim     False
gp       True
dtype: bool

In [142]:
names.isna()

jane    False
Bil     False
elon    False
tom      True
tim     False
gp       True
dtype: bool

In [143]:
names.isna().any()

np.True_

In [144]:
names_without_na=names.dropna(inplace=False)

In [145]:
names

jane    90.0
Bil     80.0
elon    85.0
tom      NaN
tim     95.0
gp       NaN
dtype: float64

In [146]:
names.isnull()

jane    False
Bil     False
elon    False
tom      True
tim     False
gp       True
dtype: bool

In [147]:
names_without_na

jane    90.0
Bil     80.0
elon    85.0
tim     95.0
dtype: float64

In [148]:
names["Ronit"]=np.nan

In [149]:
names

jane     90.0
Bil      80.0
elon     85.0
tom       NaN
tim      95.0
gp        NaN
Ronit     NaN
dtype: float64

In [150]:
names.fillna(10,inplace=True)

jane     90.0
Bil      80.0
elon     85.0
tom      10.0
tim      95.0
gp       10.0
Ronit    10.0
dtype: float64

In [151]:
names

jane     90.0
Bil      80.0
elon     85.0
tom      10.0
tim      95.0
gp       10.0
Ronit    10.0
dtype: float64

In [152]:
names_without_na

jane    90.0
Bil     80.0
elon    85.0
tim     95.0
dtype: float64

## Data Frame

In [153]:
## creating a dataframe

data={
    "name":["bill","tom","tim","john","alex","vanessa","kate"],
    "score":[90,80,85,75,95,60,65],
    "sport":["wrestling","football","skiing","swimming","tennis","karete","surfing"],
    "gender":["M","M","M","M","F","F","F"]
}

df=pd.DataFrame(data)

In [154]:
df

      name  score      sport gender
0     bill     90  wrestling      M
1      tom     80   football      M
2      tim     85     skiing      M
3     john     75   swimming      M
4     alex     95     tennis      F
5  vanessa     60     karete      F
6     kate     65    surfing      F

In [155]:
interested_col_df=df[["name","score","sport"]]

In [156]:
interested_col_df

      name  score      sport
0     bill     90  wrestling
1      tom     80   football
2      tim     85     skiing
3     john     75   swimming
4     alex     95     tennis
5  vanessa     60     karete
6     kate     65    surfing

In [157]:
df.head()

   name  score      sport gender
0  bill     90  wrestling      M
1   tom     80   football      M
2   tim     85     skiing      M
3  john     75   swimming      M
4  alex     95     tennis      F

In [158]:
df.tail(5)

      name  score     sport gender
2      tim     85    skiing      M
3     john     75  swimming      M
4     alex     95    tennis      F
5  vanessa     60    karete      F
6     kate     65   surfing      F

In [159]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    7 non-null      str
 1   score   7 non-null      int64
 2   sport   7 non-null      str
 3   gender  7 non-null      str
dtypes: int64(1), str(3)
memory usage: 356.0 bytes

In [160]:
df.describe()

           score
count   7.000000
mean   78.571429
std    12.817399
min    60.000000
25%    70.000000
50%    80.000000
75%    87.500000
max    95.000000

In [161]:
df.sample(n=3,random_state=42)

      name  score      sport gender
0     bill     90  wrestling      M
1      tom     80   football      M
5  vanessa     60     karete      F

In [162]:
df.columns

Index(['name', 'score', 'sport', 'gender'], dtype='str')

## Accessing and Indexing Data in Data frame

In [163]:
# Accessing a single column
name_data_frame=df["name"]
#name_data_frame
# Accessing multiple columns
df[["name","sport","score"]]

      name      sport  score
0     bill  wrestling     90
1      tom   football     80
2      tim     skiing     85
3     john   swimming     75
4     alex     tennis     95
5  vanessa     karete     60
6     kate    surfing     65

In [164]:
# Accessing a specific row by index
print(df.iloc[2]) # third row (index 2)
# Ascessing a range of rows using slicing
print(df.iloc[1:4,0:2]) # rows with indices 1 2 3

name         tim
score         85
sport     skiing
gender         M
Name: 2, dtype: object
   name  score
1   tom     80
2   tim     85
3  john     75

In [165]:
df.set_index("name",inplace=True)

In [166]:
df

         score      sport gender
name
bill        90  wrestling      M
tom         80   football      M
tim         85     skiing      M
john        75   swimming      M
alex        95     tennis      F
vanessa     60     karete      F
kate        65    surfing      F

In [167]:
df.reset_index(inplace=True)
df

      name  score      sport gender
0     bill     90  wrestling      M
1      tom     80   football      M
2      tim     85     skiing      M
3     john     75   swimming      M
4     alex     95     tennis      F
5  vanessa     60     karete      F
6     kate     65    surfing      F

In [168]:
df.set_index("name",inplace=True)
df

         score      sport gender
name
bill        90  wrestling      M
tom         80   football      M
tim         85     skiing      M
john        75   swimming      M
alex        95     tennis      F
vanessa     60     karete      F
kate        65    surfing      F

In [169]:
# acessing row by label (name)
print(df.loc["bill"])

score            90
sport     wrestling
gender            M
Name: bill, dtype: object

In [170]:
# ascessing specific value using lables
print(df.loc["bill","score"]) # score of the person at index 1

90

## Slicing

In [171]:
print(df.loc["bill":"tim", "score":"gender"])

      score      sport gender
name
bill     90  wrestling      M
tom      80   football      M
tim      85     skiing      M

In [172]:
print(df.iloc[1:4,0:3])

      score     sport gender
name
tom      80  football      M
tim      85    skiing      M
john     75  swimming      M

In [173]:
df[df["gender"]=='M']

      score      sport gender
name
bill     90  wrestling      M
tom      80   football      M
tim      85     skiing      M
john     75   swimming      M

In [174]:
print(df[(df["score"]>80) & (df["gender"]=="M")])

      score      sport gender
name
bill     90  wrestling      M
tim      85     skiing      M

In [175]:
print(df.sort_values("score",ascending=True))

         score      sport gender
name
vanessa     60     karete      F
kate        65    surfing      F
john        75   swimming      M
tom         80   football      M
tim         85     skiing      M
bill        90  wrestling      M
alex        95     tennis      F

In [176]:
print(df.sort_values(by=["gender","score"],ascending=[True,False]))

         score      sport gender
name
alex        95     tennis      F
kate        65    surfing      F
vanessa     60     karete      F
bill        90  wrestling      M
tim         85     skiing      M
tom         80   football      M
john        75   swimming      M

## Importing and Exporting data

In [177]:
dataset=pd.read_csv("datasets 2/datasets/data.txt", sep="\t")
dataset

  name  score gender
0  Tim     80      M
1  Tom     85      M
2  Kim     70      F
3  Sam     90      M
4  Efe     75      M

## Reading with CSV

In [179]:
df2=pd.read_csv("datasets 2/datasets/data.txt")
df2

  name\tscore\tgender
0          Tim\t80\tM
1          Tom\t85\tM
2          Kim\t70\tF
3          Sam\t90\tM
4          Efe\t75\tM

In [181]:
import pandas as pd
df=pd.read_csv("datasets 2/datasets/data.txt",
                 sep=",",
                 header=None,
                 names=["name", "age", "gender"]
              )
df

                  name  age  gender
0  name\tscore\tgender  NaN     NaN
1           Tim\t80\tM  NaN     NaN
2           Tom\t85\tM  NaN     NaN
3           Kim\t70\tF  NaN     NaN
4           Sam\t90\tM  NaN     NaN
5           Efe\t75\tM  NaN     NaN

In [182]:
# specifying header
df=pd.read_csv("datasets 2/datasets/data.txt",
                 sep=",",
                 header=None, 
                 names=["name","score","gender"])
df

                  name  score  gender
0  name\tscore\tgender    NaN     NaN
1           Tim\t80\tM    NaN     NaN
2           Tom\t85\tM    NaN     NaN
3           Kim\t70\tF    NaN     NaN
4           Sam\t90\tM    NaN     NaN
5           Efe\t75\tM    NaN     NaN

In [183]:
# specifying index column
df=pd.read_table("datasets 2/datasets/data.txt", sep=",", header=None, names=["name","score","sex"], index_col="name")
df

                     score  sex
name
name\tscore\tgender    NaN  NaN
Tim\t80\tM             NaN  NaN
Tom\t85\tM             NaN  NaN
Kim\t70\tF             NaN  NaN
Sam\t90\tM             NaN  NaN
Efe\t75\tM             NaN  NaN

In [184]:
# skip rows
df4=pd.read_csv("datasets 2/datasets/data.txt")
df4

  name\tscore\tgender
0          Tim\t80\tM
1          Tom\t85\tM
2          Kim\t70\tF
3          Sam\t90\tM
4          Efe\t75\tM

In [185]:
df3=pd.read_table("datasets 2/datasets/data.txt",
                  sep=",", 
                  skiprows=[0,2])
df3

   Tim\t80\tM
0  Kim\t70\tF
1  Sam\t90\tM
2  Efe\t75\tM

In [ ]:
df3=pd.read_table("datasets/data4.txt",
                  sep=",", 
                  skiprows=[0,2],
                  usecols=[0,1])
df3

In [ ]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\RONIT\.conda\envs\anaconda\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\Users\RONIT\.conda\envs\anaconda\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

## Reading with excel

In [ ]:
dataaa = pd.read_excel(r"C:\Users\RONIT\Desktop\Machine Learning\Python_libraries\Pandas\My_excel.xlsx")

In [ ]:
dataaa

      Name  Age      Course Semester gender
0    Ronit   18          AI      1st      M
1  Aashik    21        DBMS      5th      M
2     Aman   19    Web Tech      3rd      M
3   Sushan   20      Python      2nd      M
4   Manish   19           C      4th      M
5   ragini   17       music      1st      F
6     roji   21  networking      5th      F
7  ranjita   19       nurse      2nd      F

## Group By

In [ ]:
data = {'category':['A','B','A','B','A'],
        'values':[10,20,30,40,50]}
df=pd.DataFrame(data)
print(df)

  category  values
0        A      10
1        B      20
2        A      30
3        B      40
4        A      50

In [ ]:
# grop by 'category' and calculate the sun of 'values'
grouped = df.groupby('category')

grouped.sum()

          values
category
A             90
B             60

In [ ]:
game = pd.read_csv("datasets 2/datasets/vgsalesGlobale.csv")

In [ ]:
game

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [ ]:
game.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [ ]:
game.tail(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.0,0.0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.0,0.0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.0,0.0,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.0,0.0,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.0,0.0,0.01

In [ ]:
game.info()

<class 'pandas.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  str
 2   Platform      16598 non-null  str
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  str
 5   Publisher     16540 non-null  str
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), str(4)
memory usage: 1.4 MB

In [ ]:
game.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [ ]:
game.isnull()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
16593,False,False,False,False,False,False,False,False,False,False,False
16594,False,False,False,False,False,False,False,False,False,False,False
16595,False,False,False,False,False,False,False,False,False,False,False
16596,False,False,False,False,False,False,False,False,False,False,False
16597,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
game.dropna().describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16291.000000,16291.000000,16291.000000,16291.000000,16291.000000,16291.000000,16291.000000
mean,8290.190228,2006.405561,0.265647,0.147731,0.078833,0.048426,0.540910
std,4792.654450,5.832412,0.822432,0.509303,0.311879,0.190083,1.567345
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4132.500000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8292.000000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12439.500000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.480000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [ ]:
group = game.groupby("Genre")

In [ ]:
group["Global_Sales"].count()

Genre
Action          3316
Adventure       1286
Fighting         848
Misc            1739
Platform         886
Puzzle           582
Racing          1249
Role-Playing    1488
Shooter         1310
Simulation       867
Sports          2346
Strategy         681
Name: Global_Sales, dtype: int64

In [ ]:
group["Global_Sales"].describe()

               count      mean       std   min   25%    50%     75%    max
Genre
Action        3316.0  0.528100  1.156427  0.01  0.07  0.190  0.5000  21.40
Adventure     1286.0  0.185879  0.513280  0.01  0.02  0.060  0.1600  11.18
Fighting       848.0  0.529375  0.955965  0.01  0.08  0.210  0.5500  13.04
Misc          1739.0  0.465762  1.314886  0.01  0.06  0.160  0.4100  29.02
Platform       886.0  0.938341  2.585254  0.01  0.09  0.280  0.7900  40.24
Puzzle         582.0  0.420876  1.561716  0.01  0.04  0.110  0.3075  30.26
Racing        1249.0  0.586101  1.662437  0.01  0.07  0.190  0.5300  35.82
Role-Playing  1488.0  0.623233  1.707909  0.01  0.07  0.185  0.5225  31.37
Shooter       1310.0  0.791885  1.817263  0.01  0.08  0.230  0.7275  28.31
Simulation     867.0  0.452364  1.195255  0.01  0.05  0.160  0.4200  24.76
Sports        2346.0  0.567319  2.089716  0.01  0.09  0.220  0.5600  82.74
Strategy       681.0  0.257151  0.520908  0.01  0.04  0.090  0.2700   5.45